x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  redis:
    image: "bitnami/redis:latest"
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data

  postgres:
    image: pgvector/pgvector:0.6.2-pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: dembrane
      POSTGRES_USER: dembrane
      POSTGRES_PASSWORD: dembrane
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging: *default-logging

  rabbitmq:
    image: rabbitmq:3.13
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=dembrane
      - RABBITMQ_DEFAULT_PASS=dembrane
    networks:
      - default
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging: *default-logging

  directus:
    restart: unless-stopped
    build:
      context: ./directus
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 8055
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: admin@dembrane.com
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      WEBSOCKETS_ENABLED: true
      DB_CLIENT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: dembrane
      DB_PASSWORD: dembrane
      DB_DATABASE: dembrane
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
      TELEMETRY: false
      REDIS_ENABLED: true
      REDIS: redis://redis:6379
      CORS_ENABLED: true
      CORS_ORIGIN: "*"
    volumes:
      - ./directus/uploads:/directus/uploads

  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    command: /bin/sh /code/server/prod.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      - DATABASE_URL=postgresql+psycopg://dembrane:dembrane@postgres:5432/dembrane
      - RABBITMQ_URL=amqp://dembrane:dembrane@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - ADMIN_BASE_URL=${ADMIN_BASE_URL}
      - PARTICIPANT_BASE_URL=${PARTICIPANT_BASE_URL}
      - BUILD_VERSION=${BUILD_VERSION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISABLE_SENTRY=${DISABLE_SENTRY:-0}
      - SERVE_API_DOCS=${SERVE_API_DOCS:-0}
      - DISABLE_REDACTION=1
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/code/server/uploads
      - ./server/trankit_cache:/code/server/trankit_cache
    networks:
      - default
    depends_on:
      - directus
      - postgres
      - rabbitmq
    logging: *default-logging

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: /bin/sh /code/server/prod-worker.sh
    environment:
      - DATABASE_URL=postgresql+psycopg://dembrane:dembrane@postgres:5432/dembrane
      - RABBITMQ_URL=amqp://dembrane:dembrane@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - ADMIN_BASE_URL=${ADMIN_BASE_URL}
      - PARTICIPANT_BASE_URL=${PARTICIPANT_BASE_URL}
      - BUILD_VERSION=${BUILD_VERSION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISABLE_SENTRY=${DISABLE_SENTRY:-0}
      - SERVE_API_DOCS=${SERVE_API_DOCS:-0}
      - DISABLE_REDACTION=1
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/code/server/uploads
      - ./server/trankit_cache:/code/server/trankit_cache
    networks:
      - default
    depends_on:
      - api-server
    logging: *default-logging

  dashboard-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}/api
        - VITE_PARTICIPANT_BASE_URL=${PARTICIPANT_BASE_URL}
        - VITE_BUILD_VERSION=${BUILD_VERSION}
        - VITE_USE_PARTICIPANT_ROUTER=0
        - VITE_DIRECTUS_PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
    restart: unless-stopped
    depends_on:
      - api-server
    logging: *default-logging
    labels:
      - caddy_0.basicauth.0_dembrane=${CADDY_HASHED_PASSWORD}

  participant-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}/api
        - VITE_PARTICIPANT_BASE_URL=${PARTICIPANT_BASE_URL}
        - VITE_BUILD_VERSION=${BUILD_VERSION}
        - VITE_USE_PARTICIPANT_ROUTER=1
        - VITE_DIRECTUS_PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - dashboard-frontend
    logging: *default-logging

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - default

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    networks:
      - default
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
        EOF
        /run.sh
    networks:
      - default
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    labels:
      - caddy_0.basicauth.0_dembrane=${CADDY_HASHED_PASSWORD}

volumes:
  loki_data:
  grafana_data:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  default:
    driver: bridge
