version: '3'

services:

  dashboard-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://api.findcommonground.app/api
        - VITE_PARTICIPANT_BASE_URL=https://participant.findcommonground.app
        - VITE_USE_PARTICIPANT_ROUTER=0
    restart: unless-stopped
  
  participant-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://api.findcommonground.app/api
        - VITE_PARTICIPANT_BASE_URL=https://participant.findcommonground.app
        - VITE_USE_PARTICIPANT_ROUTER=1
    restart: unless-stopped
    networks:
      - default

  api-server:
    build: ./server
    restart: unless-stopped
    command: /bin/sh /code/server/prod.sh
    environment:
      - DATABASE_URL=postgresql+psycopg://dembrane:dembrane@postgres:5432/dembrane
    env_file:
      - ./server/.env
    volumes:
      - ./server:/code/server
    networks:
      - default
  
  postgres:
    image: postgres:15
    restart: unless-stopped
    networks:
      - default
    environment:
      POSTGRES_DB: dembrane
      POSTGRES_USER: dembrane
      POSTGRES_PASSWORD: dembrane
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  caddy:
    image: caddy:2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config 
    networks:
      - default

networks:
  default:
    driver: bridge