"""add progress for conversation

Revision ID: 788c341044cc
Revises: 7073d6e9fd01
Create Date: 2024-04-24 07:05:19.164344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import dembrane

# revision identifiers, used by Alembic.
revision: str = "788c341044cc"
down_revision: Union[str, None] = "7073d6e9fd01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation", sa.Column("progress", sa.Integer(), nullable=False))
    op.add_column(
        "conversation", sa.Column("progress_text", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "progress_text")
    op.drop_column("conversation", "progress")
    # ### end Alembic commands ###
