"""link insights with analysis

Revision ID: 7a3dbdc205ed
Revises: fe515adaad0f
Create Date: 2024-04-26 08:32:29.417149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import dembrane


# revision identifiers, used by Alembic.
revision: str = "7a3dbdc205ed"
down_revision: Union[str, None] = "fe515adaad0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "insight", sa.Column("project_analysis_run_id", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        None, "insight", "project_analysis_run", ["project_analysis_run_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "insight", type_="foreignkey")
    op.drop_column("insight", "project_analysis_run_id")
    # ### end Alembic commands ###
