"""remove processing cchunk


Revision ID: e69bb172688b
Revises: fdf5f587e7d8
Create Date: 2024-06-21 10:08:32.616846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e69bb172688b'
down_revision: Union[str, None] = 'fdf5f587e7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_chunk', sa.Column('task_id', sa.String(), nullable=True))
    op.drop_column('conversation_chunk', 'processing_started_at')
    op.drop_column('conversation_chunk', 'processing_completed_at')
    op.drop_column('conversation_chunk', 'processing_status')
    op.drop_column('conversation_chunk', 'processing_error')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_chunk', sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversation_chunk', sa.Column('processing_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('conversation_chunk', sa.Column('processing_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('conversation_chunk', sa.Column('processing_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('conversation_chunk', 'task_id')
    # ### end Alembic commands ###
