"""add representative quotes

Revision ID: fdf5f587e7d8
Revises: 3132c952c238
Create Date: 2024-06-20 12:48:38.787323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf5f587e7d8'
down_revision: Union[str, None] = '3132c952c238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('representative_quote_aspect_association',
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.Column('aspect_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspect.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.PrimaryKeyConstraint('quote_id', 'aspect_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('representative_quote_aspect_association')
    # ### end Alembic commands ###
