"""add analysis

Revision ID: fe515adaad0f
Revises: e6c4ff352695
Create Date: 2024-04-25 12:01:39.685718

"""

from typing import Sequence, Union

from alembic import op
import dembrane
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe515adaad0f"
down_revision: Union[str, None] = "e6c4ff352695"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_analysis_run",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            dembrane.database.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            dembrane.database.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("processing_status", sa.String(), nullable=False),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column(
            "processing_started_at",
            dembrane.database.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "processing_completed_at",
            dembrane.database.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "quote", sa.Column("project_analysis_run_id", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        None, "quote", "project_analysis_run", ["project_analysis_run_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quote", type_="foreignkey")
    op.drop_column("quote", "project_analysis_run_id")
    op.drop_table("project_analysis_run")
    # ### end Alembic commands ###
