"""nullable centroid

Revision ID: 090e2273a7c7
Revises: 6bf902b29f50
Create Date: 2024-06-19 12:26:42.615740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import dembrane
import pgvector

# revision identifiers, used by Alembic.
revision: str = '090e2273a7c7'
down_revision: Union[str, None] = '6bf902b29f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aspect', 'centroid_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aspect', 'centroid_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               nullable=False)
    # ### end Alembic commands ###
