"""
add user agent

Revision ID: 1baf5a7323ea
Revises: 6dac3446e224
Create Date: 2024-03-20 17:32:14.130695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1baf5a7323ea'
down_revision: Union[str, None] = '6dac3446e224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('participant_user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'participant_user_agent')
    # ### end Alembic commands ###
