"""add view, aspect

Revision ID: 2bb7f386af4e
Revises: 7f651c9b78cd
Create Date: 2024-06-19 11:14:59.905879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import dembrane
import pgvector

# revision identifiers, used by Alembic.
revision: str = '2bb7f386af4e'
down_revision: Union[str, None] = '7f651c9b78cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', dembrane.database.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', dembrane.database.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('project_analysis_run_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_analysis_run_id'], ['project_analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aspect',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', dembrane.database.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', dembrane.database.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('long_summary', sa.Text(), nullable=True),
    sa.Column('view_id', sa.String(), nullable=True),
    sa.Column('centroid_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('project_analysis_run_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_analysis_run_id'], ['project_analysis_run.id'], ),
    sa.ForeignKeyConstraint(['view_id'], ['view.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aspect')
    op.drop_table('view')
    # ### end Alembic commands ###
