"""chunk.path not null

Revision ID: 30041bf9b22e
Revises: 7a3dbdc205ed
Create Date: 2024-05-09 11:39:34.545937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30041bf9b22e"
down_revision: Union[str, None] = "7a3dbdc205ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation_chunk", "path", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation_chunk", "path", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
