"""add image url aspect

Revision ID: 3132c952c238
Revises: b75f458eef85
Create Date: 2024-06-20 12:02:43.688259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3132c952c238'
down_revision: Union[str, None] = 'b75f458eef85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aspect', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aspect', 'image_url')
    # ### end Alembic commands ###
