"""add timestamp

Revision ID: 339788dcde81
Revises: ff780e9fd87a
Create Date: 2024-03-15 10:00:56.334832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339788dcde81'
down_revision: Union[str, None] = 'ff780e9fd87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_chunk', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_chunk', 'timestamp')
    # ### end Alembic commands ###
