"""remove unique constraint on view

Revision ID: 6bf902b29f50
Revises: 2bb7f386af4e
Create Date: 2024-06-19 11:22:20.459284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf902b29f50'
down_revision: Union[str, None] = '2bb7f386af4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_aspect_association',
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.Column('aspect_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspect.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.PrimaryKeyConstraint('quote_id', 'aspect_id')
    )
    op.drop_constraint('view_name_key', 'view', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('view_name_key', 'view', ['name'])
    op.drop_table('quote_aspect_association')
    # ### end Alembic commands ###
