"""tags

Revision ID: 7073d6e9fd01
Revises: eb01d5cc0695
Create Date: 2024-04-16 13:49:06.148040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import dembrane


# revision identifiers, used by Alembic.
revision: str = "7073d6e9fd01"
down_revision: Union[str, None] = "eb01d5cc0695"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_tag",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            dembrane.database.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            dembrane.database.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_conversation_tag_association",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("project_tag", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_tag"],
            ["project_tag.id"],
        ),
        sa.PrimaryKeyConstraint("conversation_id", "project_tag"),
    )
    op.drop_table("conversation_conversation_tag_association")
    op.drop_table("conversation_tag")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_conversation_tag_association",
        sa.Column("conversation_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "conversation_tag_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
            name="conversation_conversation_tag_association_conversation_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_tag_id"],
            ["conversation_tag.id"],
            name="conversation_conversation_tag_associat_conversation_tag_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "conversation_id",
            "conversation_tag_id",
            name="conversation_conversation_tag_association_pkey",
        ),
    )
    op.create_table(
        "conversation_tag",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("color", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="conversation_tag_pkey"),
        sa.UniqueConstraint("text", name="conversation_tag_text_key"),
    )
    op.drop_table("project_conversation_tag_association")
    op.drop_table("project_tag")
    # ### end Alembic commands ###
