"""conversation finish text

Revision ID: 7f651c9b78cd
Revises: 30041bf9b22e
Create Date: 2024-05-10 04:36:21.089779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f651c9b78cd'
down_revision: Union[str, None] = '30041bf9b22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('default_conversation_finish_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'default_conversation_finish_text')
    # ### end Alembic commands ###
