"""add participant_name

Revision ID: b2976face11b
Revises: 1baf5a7323ea
Create Date: 2024-03-28 08:10:32.927016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2976face11b'
down_revision: Union[str, None] = '1baf5a7323ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('participant_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'participant_name')
    # ### end Alembic commands ###
