"""nullable aspect name

Revision ID: b75f458eef85
Revises: 090e2273a7c7
Create Date: 2024-06-20 07:09:37.379665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75f458eef85'
down_revision: Union[str, None] = '090e2273a7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aspect_name_key', 'aspect', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('aspect_name_key', 'aspect', ['name'])
    # ### end Alembic commands ###
