"""add pkey to associations

Revision ID: de60ad9cc628
Revises: 5e1cc3338573
Create Date: 2024-06-24 11:14:36.800500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de60ad9cc628'
down_revision: Union[str, None] = '5e1cc3338573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversation_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True))
    op.add_column('chat_resource_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True))
    op.add_column('conversation_chunk_quote_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True))
    op.add_column('project_conversation_tag_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True))
    op.add_column('quote_aspect_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True))
    op.add_column('representative_quote_aspect_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('representative_quote_aspect_association', 'id')
    op.drop_column('quote_aspect_association', 'id')
    op.drop_column('project_conversation_tag_association', 'id')
    op.drop_column('conversation_chunk_quote_association', 'id')
    op.drop_column('chat_resource_association', 'id')
    op.drop_column('chat_conversation_association', 'id')
    # ### end Alembic commands ###
