"""document original filename

Revision ID: e59a897f709f
Revises: 78ae5d1b0fa4
Create Date: 2024-02-29 15:39:33.297181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59a897f709f'
down_revision: Union[str, None] = '78ae5d1b0fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('original_filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'original_filename')
    # ### end Alembic commands ###
