"""add progress

Revision ID: e6c4ff352695
Revises: 788c341044cc
Create Date: 2024-04-25 11:00:19.820428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import server
import pgvector


# revision identifiers, used by Alembic.
revision: str = "e6c4ff352695"
down_revision: Union[str, None] = "788c341044cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "conversation_chunk_quote_association",
        sa.Column("conversation_chunk_id", sa.String(), nullable=False),
        sa.Column("quote_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_chunk_id"],
            ["conversation_chunk.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quote.id"],
        ),
        sa.PrimaryKeyConstraint("conversation_chunk_id", "quote_id"),
    )
    op.add_column(
        "conversation", sa.Column("processing_status", sa.String(), nullable=False)
    )
    op.add_column(
        "conversation", sa.Column("processing_error", sa.Text(), nullable=True)
    )
    op.add_column(
        "conversation",
        sa.Column(
            "processing_started_at",
            server.database.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column(
            "processing_completed_at",
            server.database.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.drop_column("conversation", "progress")
    op.drop_column("conversation", "progress_text")
    op.add_column(
        "conversation_chunk",
        sa.Column("processing_status", sa.String(), nullable=False),
    )
    op.add_column(
        "conversation_chunk",
        sa.Column(
            "processing_started_at",
            server.database.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "conversation_chunk",
        sa.Column(
            "processing_completed_at",
            server.database.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.drop_constraint(
        "conversation_chunk_quote_id_fkey", "conversation_chunk", type_="foreignkey"
    )
    op.drop_column("conversation_chunk", "is_processed")
    op.drop_column("conversation_chunk", "quote_id")
    op.add_column(
        "quote",
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quote", "embedding")
    op.add_column(
        "conversation_chunk",
        sa.Column("quote_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "conversation_chunk",
        sa.Column("is_processed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "conversation_chunk_quote_id_fkey",
        "conversation_chunk",
        "quote",
        ["quote_id"],
        ["id"],
    )
    op.drop_column("conversation_chunk", "processing_completed_at")
    op.drop_column("conversation_chunk", "processing_started_at")
    op.drop_column("conversation_chunk", "processing_status")
    op.add_column(
        "conversation",
        sa.Column("progress_text", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "conversation",
        sa.Column("progress", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("conversation", "processing_completed_at")
    op.drop_column("conversation", "processing_started_at")
    op.drop_column("conversation", "processing_error")
    op.drop_column("conversation", "processing_status")
    op.drop_table("conversation_chunk_quote_association")
    # ### end Alembic commands ###
