version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    environment:
      - DATABASE_URL=postgresql+psycopg://dembrane:dembrane@postgres:5432/dembrane
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:postgres
    command: sleep infinity

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: dembrane
      POSTGRES_USER: dembrane
      POSTGRES_PASSWORD: dembrane
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
