services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis_data:/bitnami/redis/data

  postgres:
    image: pgvector/pgvector:0.6.2-pg16
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dembrane
      POSTGRES_USER: dembrane
      POSTGRES_PASSWORD: dembrane
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=dembrane
      - RABBITMQ_DEFAULT_PASS=dembrane
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

  directus:
    build:
      context: ../directus
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    env_file:
      - ../directus/.env
    volumes:
      - ../directus/migrations:/directus/migrations
      - ../directus/extensions:/directus/extensions
      - ../directus/uploads:/directus/uploads
    depends_on:
      - postgres
      - redis

  devcontainer:
    build:
      context: ../server
      dockerfile: Dockerfile
      target: base
    environment:
      - DATABASE_URL=postgresql+psycopg://dembrane:dembrane@postgres:5432/dembrane
      - RABBITMQ_URL=amqp://dembrane:dembrane@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:postgres
    command: sleep infinity
    depends_on:
      - rabbitmq
      - postgres
      - redis
