services:
  postgres:
    image: pgvector/pgvector:0.6.2-pg16
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dembrane
      POSTGRES_USER: dembrane
      POSTGRES_PASSWORD: dembrane
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
  directus:
    image: directus/directus:10.12
    restart: unless-stopped
    ports:
      - 8055:8055
    environment:
      SECRET: really-secret-stuff-here
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password
      WEBSOCKETS_ENABLED: true
      MAX_PAYLOAD_SIZE: 10m
      DB_CLIENT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: dembrane
      DB_PASSWORD: dembrane
      DB_DATABASE: dembrane

  rabbitmq:
    image: rabbitmq:3.13
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=dembrane
      - RABBITMQ_DEFAULT_PASS=dembrane
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

  devcontainer:
    build:
      context: ../server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg://dembrane:dembrane@postgres:5432/dembrane
      - RABBITMQ_URL=amqp://dembrane:dembrane@rabbitmq:5672
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:postgres
    command: sleep infinity
    depends_on:
      - rabbitmq
      - postgres
