name: Lint and Type Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint_and_type_check_server:
    name: Lint and Type Check (Server)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('server/requirements.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r server/requirements.lock

      - name: Run mypy
        uses: tsuyoshicho/action-mypy@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          workdir: server

      - name: Run ruff
        uses: chartboost/ruff-action@v1
        with:
          src: './server'
